name: Codeconv

on:
  push:
    branches:
      - master

jobs:
  test-latest:
    runs-on: ubuntu-latest
    name: Create and upload coverage
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Get dependencies
        run: go get -t ./...
      - name: Run Unit tests.
        run: |
          echo "" > coverage.txt
          for d in $(go list ./... | grep -v vendor); do
            go test -race -coverprofile=profile.out -covermode=atomic "$d"
            if [ -f profile.out ]; then
              cat profile.out >> coverage.txt
              rm profile.out
            fi
          done
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
