name: CI

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  test-latest:
    runs-on: ubuntu-latest
    name: Go latest tests
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Get dependencies
        run: go get -t ./...
      - name: Run Unit tests.
        run: go test ./...
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.11','1.12','1.13' ]
    name: Go ${{ matrix.go }} tests
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -t ./...
      - name: Run Unit tests.
        run: go test ./...
